alert('Olá, seja bem vindo ao curso!');
document.getElementById('nome').value = 'Oi'; 
/*
 MÉTODO RESPONSÁVEL POR RECUPERAR ESSE ELEMENTO DENTRO DO OBJETO DO DOCUMENTO(DOM)
    .value : CORRESPONDE AO VALOR CONTIDO DENTRO DESSE ELEMENTO
QUANDO COLOCAMOS UM VALOR, ESTAMOS DIZENDO QUE AQUELE ELEMENTO TERÁ ESTE VALOR.

*/